In [55]:
import pandas as pd
print(pd.__version__)
import numpy as np

3.0.5

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [3]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

# 2. RECORD COUNT

In [7]:
df.count()

model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower              9123
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64

In [8]:
len(df)

10000

### Our data has a record count of 10,000 rows

# 3. FUEL TYPE

In [14]:
fuel_type = df['fuel_type'].unique()

fuel_type

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

### We have 3 different types of fuel: Gasoline, Diesel & Hybrid

# 4. MISSING VALUES

In [21]:
df.count()

model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower              9123
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64

### Only 2 columns have missing values. Which are columns 'horsepower' & 'acceleration'

# 5. MAX FUEL EFFICIENCY

In [20]:
asia_max = df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

asia_max

np.float64(41.2)

### The maximum fuel efficiency of cars in Asia is 41.2

# 6. MEDIAN VALUE OF HORSEPOWER

In [22]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [24]:
# Median value of the horsepower

horsepower_med = df['horsepower'].median()
horsepower_med

np.float64(254.0)

### The Median value of the horsepower is 254.0

In [29]:
### Most frequent value of the same horsepower column.
df['horsepower'].value_counts().head()

horsepower
252.0    174
246.0    168
256.0    168
259.0    165
253.0    165
Name: count, dtype: int64

### The most frequent value of the same horsepower column is 252

In [31]:
### Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step
most_frequent = df['horsepower'].value_counts().idxmax()

df['horsepower'] = df['horsepower'].fillna(most_frequent)

df['horsepower'].count()

np.int64(10000)

In [34]:
### Calculate the median value of horsepower
new_med = df['horsepower'].median()

new_med

np.float64(252.0)

### The median value of horsepower has decreased.

# 7. Sum of weights

In [35]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [39]:
# Select all the cars from Asia
new_df = df[df['origin'] == 'Asia']

new_df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [40]:
# Select only columns vehicle_weight and model_year
asia_df = new_df[['vehicle_weight', 'model_year']]

asia_df.head()

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007

In [41]:
# Select the first 7 values
asia_df_new = asia_df.head(7)

asia_df_new

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [43]:
# Get the underlying NumPy array
X = asia_df_new.values

X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [46]:
# Compute X transpose multiplied by X
XTX = X.T @ X

XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [49]:
# Invert XTX
XTX_inv = np.linalg.inv(XTX)

XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [50]:
# Create y
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [51]:
# Calculate w
w = XTX_inv @ X.T @ y

w

array([0.13644777, 0.2327492 ])

In [53]:
# Sum all elements of w
w.sum().round(3)

np.float64(0.369)

### Sum of all weights is 0.369